### ISSUE TITLE
babel plugin to reduce/remove ungap polyfill code

### ISSUE THREAD

**Issue by coreyfarrell** [ungap/ungap.github.io#3]
I've created a babel plugin to remove/reduce the code included by ungap.  The purpose is for projects that either require latest browsers or already import other polyfills.  Is this something you'd be interested in listing as an option?  If so I can add support for CJS (currently only works on ESM).  For my own project I'm using `import hyperhtml from 'hyperhtml';` (imports hyperhtml/esm/index.js) and building with rollup, babel and babel-preset-minifier.  In that project adding the "remove-ungap" babel plugin reduced the final uncompressed bundle by 2.7k.

Right now it's published as v0.1.0, I'll likely bump to 1.0.0 once I can figure out how to eliminate the variable copy for polyfills which point to non-global symbols.  For example `import isArray from '@ungap/is-array'` is replaced with `var isArray = Array.isArray` instead of simply replacing calls to `isArray` with calls to `Array.isArray`.

https://github.com/cfware/babel-plugin-remove-ungap#readme

**Comment by WebReflection** [comment]
This is awesome!

But about replacing assignments with their global lookup, I wouldn't bother cause shortcuts are faster, easier to minify, and safer (no lazy tainted env issues), so please don't remind me those in v1

**Comment by coreyfarrell** [comment]
Currently `import Map from '@ungap/essential-map';` is simply deleted and `import MapAlias from '@ungap/essential-map';` causes all references to `MapAlias` to be renamed to `Map`.  Are you suggesting that I should always replace the import with `var Map = Map;` or `var MapAlias = Map;`, minimize use of the browser globals?

Currently the variable assignment method is only done when the target is complex (Array.isArray for example is referencing a member, not an identifier).

**Comment by WebReflection** [comment]
to clarify, when I:

```js
import isArray from '@ungap/is-array';
```

I want exactly this to happen
```js
const {isArray} = Array;
```

but the good old `const isArray = Array.isArray` would be fine too.

That grants no lookup to the global scope every time I use the `isArray` variable, which is 99% of the time desirable, unless you don't want to be victim of lazy loaded polyfills that might change, or track, your code logic.


The `@ungap/essential-map` should be mapped same as `@ungap/map` 'cause both would return a `Map` sort-of constructor, and same goes for weakest, weak map, and their essential counter parts.

**Comment by coreyfarrell** [comment]
Yeah right now I use `var isArray = Array.isArray` (this is easier than the other form).

It sounds like you're suggesting that I should change the way that Map is handled.
```js
import Map from '@ungap/essential-map';
import MapAlias from '@ungap/map';

console.log(new Map());
console.log(new MapAlias());
```
Currently this gets replaced with:
```js
console.log(new Map());
console.log(new Map());
```
I did this as it was easy to manipulate the simple identifiers.  Based on avoiding global scope it sounds like you're suggesting the code should instead be:
```js
var Map = Map;
var MapAlias = Map;
console.log(new Map());
console.log(new MapAlias());
```

I'm not immediately sure how I would prevent `MapAlias` from getting `Map` though I don't think this should make a difference unless someone does something really ridiculous.  I could probably generate unique identifiers to create in place of `var Map` and `var MapAlias`, though doing that would be a bit more difficult.

**Comment by WebReflection** [comment]
I think this would be just fine:

```js
import Map from '@ungap/essential-map';
import MapAlias from '@ungap/map';
```

becoming
```js
var Map = Map;
var Map = Map;
```

alternatively, both could become
```js
var uEMap = Map;
var uMap = Map;
```

but I'd prefer the `var Map` version

**Comment by coreyfarrell** [comment]
Unfortunately this created broken rollup bundles.  Two sources containing `var Map = Map;` causes the second source to be rewritten to `var Map$1 = Map$1;`.

I tried a new approach where the actual ungap module was rewritten, so `@ungap/map/essential-esm/index.js` was modified to `export default Map;`.  This ultimately caused the final rollup bundle to directly use the global symbol `Map` everywhere (no var was declared).  So the final bundled result was the exact same as the current plugin, but this created additional complexity avoiding problems with the `rollup-plugin-babel` preflight check.

So I think I'm just going to stick with the current approach of directly using `Map`, `WeakMap` and other simple global symbols by removing `import Map from '@ungap/essential-map';`.

**Comment by WebReflection** [comment]
@coreyfarrell that is fine, but then how does the `import isArray from "@ungap/is-array"` works? Still replaced as `Array.isArray` everywhere ?

**Comment by coreyfarrell** [comment]
Nope.  Code everywhere is only edited if the translation does not declare a variable (see table) and the module was imported to an alternate name.  For example:
```js
import myIsArray from '@ungap/is-array';
import Set from '@ungap/set';
import MySet from '@ungap/set';
console.log(typeof myIsArray, typeof Set, typeof MySet);
```
`myIsArray` is declared, `MySet` references are replaced with `Set` (the native object):
```js
var myIsArray = Array.isArray;
console.log(typeof myIsArray, typeof Set, typeof Set);
```

The following table lists all imports which are removed, the native target, and if a variable is declared in place of the import.  When I get a chance I'll update the README to incorporate this information.

Module|Target|Declares variable
-|-|-
@ungap/assign|Object.assign|Yes
@ungap/array-iterator|Array.prototype[Symbol.iterator]|Yes
@ungap/custom-event|CustomEvent
@ungap/essential-map|Map
@ungap/essential-set|Set
@ungap/essential-symbol|Symbol
@ungap/essential-weakset|WeakSet
@ungap/event|Event
@ungap/event-target|EventTarget
@ungap/import-node|document.importNode|Yes
@ungap/is-array|Array.isArray|Yes
@ungap/map|Map
@ungap/set|Set
@ungap/template-literal|val => val|Yes
@ungap/trim|String.prototype.trim|Yes
@ungap/weakmap|WeakMap
@ungap/weakset|WeakSet

**Comment by WebReflection** [comment]
OK, this is super cool!

My last question would be: is it possible to define which one should be ignored and which one shouldn't?

As example, `EventTarget` is not widely compatible and `@ungap/template-literal` is complicated. Could these be left as these are, instead of being replaced?

**Comment by coreyfarrell** [comment]
Yes that's already possible.  In babelrc you can pass the [exclude option](https://github.com/cfware/babel-plugin-remove-ungap#exclude-option) to my plugin, tell it which modules should be left as is.

So you might want babelrc as such:
```js
{
	plugins: [
		['remove-ungap', {
			exclude: [
				'@ungap/event-target',
				'@ungap/template-literal'
			]
		}]
}
```

One other thing I just noticed I didn't mention in this ticket, `node_modules/@ungap/create-content/esm/index.js` is directly altered.  `var HAS_CONTENT = 'content' in create(TEMPLATE);` is replaced with `var HAS_CONTENT = true;`.  This causes the legacy version of `createHTML` to be optimized away by babel minifier.  This alteration can be disabled by adding `@ungap/create-content` to the exclude option.

**Comment by WebReflection** [comment]
I see, causing death code makes sense for this plugin 👍

**Comment by coreyfarrell** [comment]
FYI I've just released v0.1.1 which adds support for processing CJS `require` statements.

**Comment by WebReflection** [comment]
whenever you think it's usable enough, please tell me how to promote this on this very same project (maybe a PR for the site page?) or how to tweet/link about such project, thanks.

**Comment by WebReflection** [comment]
FYI I am using this wonderful plugin to create a bloat-less version of lighterhtml:
https://github.com/WebReflection/lighterhtml/blob/master/es.config.js

Thank you so much, this works like a charm!

**Comment by coreyfarrell** [comment]
That's great.  Sorry I've dropped the ball in this for a bit, I've had other commitments take over.  I notice you disabled `@ungap/create-content`.  What browser are you targeting which does not have `'content' in document.createElementNS('http://www.w3.org/1999/xhtml', 'template')`?

**Comment by WebReflection** [comment]
Not targeting any browser but that's an utility, not a polyfill

**Comment by coreyfarrell** [comment]
Well part of `@ungap/create-content` is a polyfill.  When `remove-ungap` processes `@ungap/create-content` it forces `HAS_CONTENT = true`.  So when you minify code (and possibly when rollup does tree-shaking), it'll remove everything that becomes unreachable by making `HAS_CONTENT` constant.

https://github.com/ungap/create-content/blob/master/index.js#L5

**Comment by WebReflection** [comment]
OK, I didn't realize you addressed each ungap by name, I thought it was more generic. Yes, if that's what happens, then it shouldn't be needed to exclude create content.
Will check, thanks

**Comment by coreyfarrell** [comment]
I've released v1.0.0 which adds support for `@ungap/from-entries` (not enabled by default).  Technically this is not a breaking change it's a feature / bug fix but I'm ready for this to be 1.0.0.  v1.0.0 should have no effect on your lighterhtml process - the bug fix avoids a babel crash caused by running `remove-ungap` after a plugin which inserts new variable declarations (`@babel/plugin-proposal-object-rest-spread` is what caused it for me).

`@ungap/from-entries` is only processed if requested via `future: ['@ungap/from-entries']`.  This `future` option will be used for two cases:
1. For features such as `Object.fromEntries` which are very widely unavailable in browsers (only supported by current Firefox).
2. New ungap polyfills are released and I want `remove-ungap` to support it but do not want a semver-major release yet.  New ungap polyfills will be opt-in via the `future` option to ensure backwards compatibility.

**Comment by WebReflection** [comment]
apologies I've forgotten to close this and add such feature in the README/index of `@ungap`

thanks a lot for your effort !

**Comment by coreyfarrell** [comment]
no worries, thanks for listing it.
